import type { NextPage } from "next";
import Head from "next/head";
import Books from "../components/BookList";
import Layout from "../components/Layout";
import BookList from "../components/BookList";

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Ugle</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className="flex flex-row flex-wrap gap-5">
          <BookList />
        </main>
      </Layout>
    </>
  );
};

export default Home;
